services:
  - type: web
    name: sushi-website
    env: node
    buildCommand: npm install
    startCommand: npm run deploy
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: / 